WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
| distributed init (rank 0, world 8): env://
| distributed init (rank 1, world 8): env://
| distributed init (rank 5, world 8): env://
| distributed init (rank 4, world 8): env://
| distributed init (rank 3, world 8): env://
| distributed init (rank 2, world 8): env://
| distributed init (rank 7, world 8): env://
| distributed init (rank 6, world 8): env://
2024-06-26 20:43:56,684 [INFO] 
=====  Running Parameters    =====
2024-06-26 20:43:56,685 [INFO] {
    "batch_size_eval": 32,
    "batch_size_train": 16,
    "device": "cuda",
    "dist_backend": "nccl",
    "dist_url": "env://",
    "distributed": true,
    "evaluate": true,
    "gpu": 0,
    "k_test": 128,
    "num_workers": 4,
    "output_dir": "output/BLIP2/Retrieval_Flickr30k",
    "rank": 0,
    "seed": 42,
    "task": "retrieval",
    "test_splits": [
        "test"
    ],
    "use_dist_eval_sampler": false,
    "world_size": 8
}
2024-06-26 20:43:56,685 [INFO] 
======  Dataset Attributes  ======
2024-06-26 20:43:56,685 [INFO] 
======== flickr30k =======
2024-06-26 20:43:56,685 [INFO] {
    "build_info": {
        "annotations": {
            "test": {
                "storage": "flickr30k/annotations/test.json",
                "url": "https://storage.googleapis.com/sfr-vision-language-research/datasets/flickr30k_test.json"
            }
        },
        "images": {
            "storage": "flickr30k/images"
        }
    },
    "data_type": "images",
    "text_processor": {
        "eval": {
            "name": "blip_caption"
        }
    },
    "vis_processor": {
        "eval": {
            "image_size": 364,
            "name": "blip_image_eval"
        }
    }
}
2024-06-26 20:43:56,685 [INFO] 
======  Model Attributes  ======
2024-06-26 20:43:56,686 [INFO] {
    "a_bits": 32,
    "arch": "blip2",
    "drop_path_rate": 0,
    "finetuned": "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/blip2_finetune_coco.pth",
    "freeze_vit": false,
    "image_size": 364,
    "load_finetuned": true,
    "model_type": "coco",
    "num_query_token": 32,
    "pretrained": "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/blip2_pretrained.pth",
    "use_grad_checkpoint": false,
    "vit_precision": "fp32",
    "w_bits": 8
}
CACHE_ROOT:/fs/vulcan-scratch/elau1/.cache
STORAGE_PATH:/fs/vulcan-scratch/elau1/.cache/flickr30k/annotations/test.json
Using downloaded and verified file: /fs/vulcan-scratch/elau1/.cache/flickr30k/annotations/test.json
2024-06-26 20:43:56,752 [INFO] Building datasets...
2024-06-26 20:43:56,958 [WARNING] /nfshomes/elau1/ViT/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

2024-06-26 20:43:56,959 [WARNING] /nfshomes/elau1/ViT/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

2024-06-26 20:43:56,960 [WARNING] /nfshomes/elau1/ViT/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

2024-06-26 20:43:56,963 [WARNING] /nfshomes/elau1/ViT/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

2024-06-26 20:43:56,965 [WARNING] /nfshomes/elau1/ViT/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

2024-06-26 20:43:56,966 [WARNING] /nfshomes/elau1/ViT/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

2024-06-26 20:43:56,980 [WARNING] /nfshomes/elau1/ViT/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

2024-06-26 20:43:56,996 [WARNING] /nfshomes/elau1/ViT/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Position interpolate from 16x16 to 26x26
RUNNING WITH W4 A32
Traceback (most recent call last):
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/evaluate.py", line 95, in <module>
    main()
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/evaluate.py", line 86, in main
    model = task.build_model(cfg)
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/tasks/base_task.py", line 33, in build_model
    return model_cls.from_config(model_config)
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/models/blip2_models/blip2_qformer.py", line 519, in from_config
    model = cls(
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/models/blip2_models/blip2_qformer.py", line 86, in __init__
    self.text_proj = NBitLinearDynamic(self.Qformer.config.hidden_size, embed_dim, weight_bits=weight_bits, activtion_bits=activation_bits)
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/models/layers/nbitlineardynamic.py", line 81, in __init__
    super().__init__(*kargs, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'activtion_bits'
Traceback (most recent call last):
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/evaluate.py", line 95, in <module>
    main()
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/evaluate.py", line 86, in main
    model = task.build_model(cfg)
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/tasks/base_task.py", line 33, in build_model
    return model_cls.from_config(model_config)
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/models/blip2_models/blip2_qformer.py", line 519, in from_config
    model = cls(
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/models/blip2_models/blip2_qformer.py", line 86, in __init__
    self.text_proj = NBitLinearDynamic(self.Qformer.config.hidden_size, embed_dim, weight_bits=weight_bits, activtion_bits=activation_bits)
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/models/layers/nbitlineardynamic.py", line 81, in __init__
    super().__init__(*kargs, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'activtion_bits'
Traceback (most recent call last):
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/evaluate.py", line 95, in <module>
    main()
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/evaluate.py", line 86, in main
    model = task.build_model(cfg)
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/tasks/base_task.py", line 33, in build_model
    return model_cls.from_config(model_config)
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/models/blip2_models/blip2_qformer.py", line 519, in from_config
    model = cls(
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/models/blip2_models/blip2_qformer.py", line 86, in __init__
    self.text_proj = NBitLinearDynamic(self.Qformer.config.hidden_size, embed_dim, weight_bits=weight_bits, activtion_bits=activation_bits)
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/models/layers/nbitlineardynamic.py", line 81, in __init__
    super().__init__(*kargs, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'activtion_bits'
Traceback (most recent call last):
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/evaluate.py", line 95, in <module>
    main()
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/evaluate.py", line 86, in main
    model = task.build_model(cfg)
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/tasks/base_task.py", line 33, in build_model
    return model_cls.from_config(model_config)
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/models/blip2_models/blip2_qformer.py", line 519, in from_config
    model = cls(
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/models/blip2_models/blip2_qformer.py", line 86, in __init__
    self.text_proj = NBitLinearDynamic(self.Qformer.config.hidden_size, embed_dim, weight_bits=weight_bits, activtion_bits=activation_bits)
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/models/layers/nbitlineardynamic.py", line 81, in __init__
    super().__init__(*kargs, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'activtion_bits'
Traceback (most recent call last):
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/evaluate.py", line 95, in <module>
    main()
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/evaluate.py", line 86, in main
    model = task.build_model(cfg)
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/tasks/base_task.py", line 33, in build_model
    return model_cls.from_config(model_config)
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/models/blip2_models/blip2_qformer.py", line 519, in from_config
    model = cls(
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/models/blip2_models/blip2_qformer.py", line 86, in __init__
    self.text_proj = NBitLinearDynamic(self.Qformer.config.hidden_size, embed_dim, weight_bits=weight_bits, activtion_bits=activation_bits)
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/models/layers/nbitlineardynamic.py", line 81, in __init__
    super().__init__(*kargs, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'activtion_bits'
Traceback (most recent call last):
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/evaluate.py", line 95, in <module>
    main()
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/evaluate.py", line 86, in main
    model = task.build_model(cfg)
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/tasks/base_task.py", line 33, in build_model
    return model_cls.from_config(model_config)
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/models/blip2_models/blip2_qformer.py", line 519, in from_config
    model = cls(
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/models/blip2_models/blip2_qformer.py", line 86, in __init__
    self.text_proj = NBitLinearDynamic(self.Qformer.config.hidden_size, embed_dim, weight_bits=weight_bits, activtion_bits=activation_bits)
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/models/layers/nbitlineardynamic.py", line 81, in __init__
    super().__init__(*kargs, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'activtion_bits'
Traceback (most recent call last):
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/evaluate.py", line 95, in <module>
    main()
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/evaluate.py", line 86, in main
    model = task.build_model(cfg)
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/tasks/base_task.py", line 33, in build_model
    return model_cls.from_config(model_config)
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/models/blip2_models/blip2_qformer.py", line 519, in from_config
    model = cls(
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/models/blip2_models/blip2_qformer.py", line 86, in __init__
    self.text_proj = NBitLinearDynamic(self.Qformer.config.hidden_size, embed_dim, weight_bits=weight_bits, activtion_bits=activation_bits)
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/models/layers/nbitlineardynamic.py", line 81, in __init__
    super().__init__(*kargs, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'activtion_bits'
Traceback (most recent call last):
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/evaluate.py", line 95, in <module>
    main()
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/evaluate.py", line 86, in main
    model = task.build_model(cfg)
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/tasks/base_task.py", line 33, in build_model
    return model_cls.from_config(model_config)
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/models/blip2_models/blip2_qformer.py", line 519, in from_config
    model = cls(
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/models/blip2_models/blip2_qformer.py", line 86, in __init__
    self.text_proj = NBitLinearDynamic(self.Qformer.config.hidden_size, embed_dim, weight_bits=weight_bits, activtion_bits=activation_bits)
  File "/fs/vulcan-scratch/elau1/copies/lavis-clone2/lavis/models/layers/nbitlineardynamic.py", line 81, in __init__
    super().__init__(*kargs, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'activtion_bits'
[2024-06-26 20:46:01,761] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 322689) of binary: /nfshomes/elau1/ViT/bin/python
Traceback (most recent call last):
  File "/opt/local/stow/Python3-3.9.12/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/local/stow/Python3-3.9.12/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/nfshomes/elau1/ViT/lib/python3.9/site-packages/torch/distributed/run.py", line 816, in <module>
    main()
  File "/nfshomes/elau1/ViT/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/nfshomes/elau1/ViT/lib/python3.9/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/nfshomes/elau1/ViT/lib/python3.9/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/nfshomes/elau1/ViT/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/nfshomes/elau1/ViT/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
evaluate.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-06-26_20:46:01
  host      : vulcan41.umiacs.umd.edu
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 322690)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-06-26_20:46:01
  host      : vulcan41.umiacs.umd.edu
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 322691)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-06-26_20:46:01
  host      : vulcan41.umiacs.umd.edu
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 322692)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2024-06-26_20:46:01
  host      : vulcan41.umiacs.umd.edu
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 322693)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2024-06-26_20:46:01
  host      : vulcan41.umiacs.umd.edu
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 322694)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2024-06-26_20:46:01
  host      : vulcan41.umiacs.umd.edu
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 322695)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2024-06-26_20:46:01
  host      : vulcan41.umiacs.umd.edu
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 322696)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-06-26_20:46:01
  host      : vulcan41.umiacs.umd.edu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 322689)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
